name: Comment on PRs associated with latest release

on:
  push:
    branches: [issues/8176/tag-release-related-to-pr]
#   release:
#     types: [published]

jobs:
  comment-on-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Release Information
        id: get-release
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'ohcnetwork',
              repo: 'care_fe'
            });
            const tagName = response.data.tag_name;
            console.log(`Latest release tag: ${tagName}`);
            core.setOutput('latest_tag', tagName);
      - name: Get Merged PRs
        id: get-prs
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = core.getInput('tag_name');
            const listPullRequestsAssociatedWithRelease = async (tagName) => {
              const response = await fetch(`https://github.com/ohcnetwork/care_fe/releases/tag/v24.47.0`);
              const domText = await response.text();
              const parser = new DOMParser();
              const doc = parser.parseFromString(domText, 'text/html');
              console.log(doc);
              return response.data;
            };
            const prs = await listPullRequestsAssociatedWithRelease(tagName);
            console.log(prs)
            core.setOutput('prs', JSON.stringify(prs));
      - name: Comment on PRs
        uses: actions/github-script@v6
        with:
          script: |
            const prs = JSON.parse(core.getInput('prs'));
            prs.forEach(pr => {
              console.log({
                issue_number: pr.number,
                owner: `ohcnetwork`,
                repo: `care_fe`,
                body: `This PR was merged into the **${core.getInput('tag_name')}** release.`
              })
            });
