name: Comment on PRs associated with latest release

on:
  push:
    branches: [issues/8176/tag-release-related-to-pr]
#   release:
#     types: [published]

jobs:
  comment-on-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Release Information
        id: get-release
        uses: actions/github-script@v6
        with:
          script: |
            const release = context.payload.release;
            console.log(release.tag_name);
            core.setOutput('tag_name', release.tag_name);
      - name: Get Merged PRs
        id: get-prs
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = core.getInput('tag_name');
            const listPullRequestsAssociatedWithRelease = async (tagName) => {
              const response = await github.rest.pulls.list({
                owner: `ohcnetwork`,
                repo: `care_fe`,
                state: 'closed',
                base: tagName
              });
              return response.data;
            };
            const prs = await listPullRequestsAssociatedWithRelease(tagName);
            core.setOutput('prs', JSON.stringify(prs));
      - name: Comment on PRs
        uses: actions/github-script@v6
        with:
          script: |
            const prs = JSON.parse(core.getInput('prs'));
            prs.forEach(pr => {
              console.log({
                issue_number: pr.number,
                owner: `ohcnetwork`,
                repo: `care_fe`,
                body: `This PR was merged into the **${core.getInput('tag_name')}** release.`
              })
            });
